### ISSUE TITLE
New released v0.1.1 missing.

### ISSUE THREAD

**Issue by 0ndorio** [rustyhorde/slog-try#1]
The [crates.io](https://crates.io/crates/slog-try) page of this project claims that there is a new released version with the tag `v0.1.1` which seems to be missing from this repository.

Could you please check that out and add the missing commits or provide me a link to an updated repository?

It also seems like you had some bad luck with the timing of your update. `slog` released a bigger update two days ago (v.2.2.2) and your strict version enforcement doesn't allow to compile against it.

**Comment by CraZySacX** [comment]
Actually, I pinned my slog version to 2.1.1 until I'm able to fix the issues caused by the new slog release.  Pushed to my personal repo and forgot to push here.  ssh is blocked at work so I'll push around noon eastern.

**Comment by 0ndorio** [comment]
Thanks for the quick response :+1:

**Comment by CraZySacX** [comment]
I've pushed the latest here.   This is should be resolved.
